name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Create google-services.json
        shell: bash
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }} # Repository Secret을 읽어옴

      # --- 2. Push(main 브랜치)일 때만 실행되는 릴리즈 단계 ---
      - name: Setup Release Files (Keystore, Properties)
        shell: bash
        run: |
          # 1. Keystore 파일 생성
          echo "${{ secrets.STORE_FILE }}" | base64 --decode > ${{ github.workspace }}/pwfb-keystore.jks
          
          # 2. local.properties 생성
          # (storeFile에 방금 위에서 생성한 파일의 '정확한 경로'를 지정)
          cat > local.properties <<EOF
          sdk.dir=$ANDROID_SDK_ROOT
          storeFile=${{ github.workspace }}/pwfb-keystore.jks
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          storePassword=${{ secrets.STORE_PASSWORD }}
          AdMobAPI_KEY=${{ secrets.ADMOB_API_KEY }}
          EOF    

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 테스트
      - name: Test & Lint
        run: ./gradlew lint testDebugUnitTest

      # Push일 때 디버그 빌드 실행
      - name: Assemble Debug (Test)
        if: github.event_name == 'push'
        run: ./gradlew assembleDebug

      # Push일 때만 디버그 이름 변경
      - name: Rename Debug APK to pwfb.apk
        if: github.event_name == 'push'
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/pwfb_debug.apk

      # Push일 때 디버그 apk 업로드
      - name: Upload Debug APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: pwfb_debug
          path: app/build/outputs/apk/debug/pwfb_debug.apk

      # Push일 때만 릴리즈 빌드 실행
      - name: Assemble Release
        if: github.event_name == 'push'
        run: ./gradlew assembleRelease

      # Push일 때 릴리즈 이름 변경
      - name: Rename Release APK to pwfb.apk
        if: github.event_name == 'push'
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/pwfb_release.apk

      # Push일 때만 릴리즈 업로드
      - name: Upload Release APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: pwfb_release
          path: app/build/outputs/apk/release/pwfb_release.apk